### PR TITLE
Add faq

### PR DESCRIPTION
**Pull request by RichardLitt**
So, I've started adding in a FAQ. It needs some help, but I think it's a good start. It might be a good idea to merge it in and just work on it collaboratively here, rather than in issues which don't actually keep track of versioning and don't lend themselves towards building a living document. 

Ideally, this would actually be part of the README which is the index of the website. What do you think?

### CODE REVIEW

**Comment by RichardLitt** [comment]
@sethwoodworth thoughts?

**Comment by eshellman** [comment]
seems as good a start as any

**Comment by sethwoodworth** [comment]
Ah, that is why I never merged the PR. Github pages still breaks when trying to build the GITenberg pages branch :-1: I just received an email with:
```
The page build failed with the following error:

page build timed out

If you have any questions please contact us at https://github.com/contact.
```

**Comment by sethwoodworth** [comment]
There have been a lot of crashes related to having so many github repos.  I will reach out to support and see if I can get a response.  If not, we'll find another way.  Thank you for getting this FAQ started!

**Comment by RichardLitt** [comment]
Darn. Well, there should be some way, at some point, to do this. No problem.

**Comment by sethwoodworth** [comment]
Wow. It turns out, adding a `.nojekyll` file to the repo makes it work!

Your PR is up:

https://gitenberg.github.io/FAQ.md

**Comment by RichardLitt** [comment]
:D Awesome.

**Comment by gitenjar** [comment]
We should start a wikipage to compile a list of things that break with large numbers of repos.

My two contributions: GitHub for Mac and email notifications to Flowdock.

**Comment by RichardLitt** [comment]
I would go through and close the open issues in this repo that are now in the FAQ, @sethwoodworth.

**Pull request merged**
